language: python
python:
  - '2.7'
script: ./deploy
before_install:
 - sudo apt-get update -y
 - sudo apt-get install -y libdb-dev
 - wget -qO- https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz | tar xvz
 - cd Python-2.7.9
 - ./configure
 - make
 - sudo make install
 - ./python -c "import bsddb;print 'worked'"
 - cd ..
 - virtualenv -p /usr/local/bin/python2.7 venv
 - . venv/bin/activate
env:
 global:
   - GH_REF: github.com/pythonindia/planet-python-india
   - secure: CzIjcrZi/0ohN/NAfOdetD+2i0eCLYb4b9VUU4tRTBYFaHuyjcu+7uwuHI0Wv+m9OpoKCqVwnIrmBM/j6/e3XyWlyFk4AEbhz7gyKJsfozYKJu/11Onrtz4kbCt0iCuqCYAm5/mNrGxO9oEczf5i6f+Fzz07jhj+3ej4qbc486U=
